### ISSUE TITLE
Pre-existing aspect values missing

### ISSUE THREAD

**Issue by Reassembly** [Parker8283/ThaumcraftMobAspects#1]
Suggestion: When populating the config files, rather than adding null entries for all mobs/entities that are not explicitly supported, it would be helpful if the _existing_ entity aspects added by Thaumcraft (or other mods with built-in Thaumcraft aspects) could be fetched and used to populate the configuration entries, to expose the base values for further adjustment.

**Comment by usafphoenix** [comment]
YES, PLEASE. upon adding mod and going into config folder, i was like..... >.< nope!!!!
