### ISSUE TITLE
no aspects

### ISSUE THREAD

**Issue by shadoxxhd** [Parker8283/ThaumcraftMobAspects#3]
TMA somehow deleted all vanilla mob aspects (blank config files, it should leave these intact instead of clearing everything)

**Comment by Parker8283** [comment]
I _believe_ that is to be intentional, as then pack makers can assign different aspects to vanilla mobs. I could be wrong. I'll check it out when I have time.

**Comment by shadoxxhd** [comment]
but then it would be awesome if the config files would contain the standard
aspects as a preset, so you dont have to manually enter the standard
aspects if the only reason for installing the mod is to add aspects to
previously unsupported entities form some mods (or wither skeletons, it
seems like they dont drop any vis bubbles for recharging your wand)

**Comment by Reassembly** [comment]
This is the same issue as #1 - which is now over a year old, sadly.
