### ISSUE TITLE
My Modpack crashes when using Big Reactors and Thaumcraft Mob Aspects

### ISSUE THREAD

**Issue by Luysita** [Parker8283/ThaumcraftMobAspects#5]
Hello, I added Big Reactors to my personal modpack today and it crashes when using Thaumcraft mob aspects. I am using MultiMC launcher and forge 1517.
I disabled Thaumcraft mob aspects from the mod list and now worked fine, but I really want to use both mods.
Is there a fix? Thank you.

http://pastebin.com/cew3fSpb

Big reactors version: BigReactors-0.4.3A
Thaumcraft mob aspects version: ThaumcraftMobAspects-1.7.2-2A

**Comment by Parker8283** [comment]
Looks like a bad config file. Check to make sure your config files aren't malformed.

**Comment by Luysita** [comment]
I removed both TMA and BigReactors configs and now seems to be working fine.
Thank you so much for the response!
